### ISSUE TITLE
Expose free disk space, RAM, and CPU via /metrics

### ISSUE THREAD

**Issue by missytake** [deltachat/chatmail#183]
This way, we could automatically decide which chatmail server is suited for onboarding a new user.

**Comment by nudeldudel** [comment]
I suggest sysstat. With the tools of it, you cann fetch nice informations via the commandline.

**Comment by hagenest** [comment]
hm, how about a flag that automatically deploys node-exporter for prometheus / grafana? And if not set, we expose the metrics like you proposed. Or is this overkill?

**Comment by nudeldudel** [comment]
Yes, it makes sense.

Christian Hagenest ***@***.***> schrieb am Fr., 17. Mai 2024,
18:03:

**Comment by hpk42** [comment]
similarly to https://github.com/deltachat/chatmail/issues/38 i close this monitoring issue because it's for now a rather orthogonal issue and there are many ways to approach monitoring/tracking resource usage. 
If needed, let's discuss what precisely we want to add in terms of monitoring to chatmail-servers themselves and then create an issue.  Closing this one here.
