### ISSUE TITLE
Remove old accounts

### ISSUE THREAD

**Issue by link2xt** [deltachat/chatmail#295]
At least `ci-` accounts can be removed. Currently running "Fix file owner in /home/vmail" steps takes a long time because it has to go through a lot of directories.

We also should drop "Fix file owner in /home/vmail" step eventually.

**Comment by hagenest** [comment]
As it was requested again, we could auto-remove accounts and their mails after n days. Holger mentioned we could use this: https://doc.dovecot.org/configuration_manual/lastlogin_plugin/

**Comment by hagenest** [comment]
guys, nami and me just found out, that we already save the last login in doveauth.py (l 107)

```
        if userdata:
            # Update last login time.
            conn.execute(
                "UPDATE users SET last_login=? WHERE addr=?", (int(time.time()), user)
            )
```

**Comment by hpk42** [comment]
so we change the database on every login -- hum.  Maybe the "int" should be of day granularity so we don't update very often and also keep less precise track of login-times in the DB.  Something like `time.time() // 86400 * 86400`  should do the job.    Also, i am wondering now regarding mail-sending: in order to send mail, you need to login -- and postfix calls doveauth for that, so we shouldn't really need to do anything extra, no?
