### ISSUE TITLE
Setup monitoring

### ISSUE THREAD

**Issue by link2xt** [deltachat/chatmail#38]
`postqueue -j` prints postfix queue in JSON, can be redirected into `wc -l` to count the number of messages and counted with [RRDtool](https://oss.oetiker.ch/rrdtool) or some monitoring system based on it, but we can also use https://oss.oetiker.ch/rrdtool/prog/rrdpython.en.html directly.

**Comment by hpk42** [comment]
at least nine.testrun.org has monitoring and our italian friends have their own solution https://chaos.social/deck/@roughnecks@livellosegreto.it/112860670223898339  -- there is pressing need to integrate monitoring into chatmail servers at this point.  So i close this quite issues which didn't see any comments since 8 months.
