### ISSUE TITLE
Problem with update file: `/chatmaild/src/chatmaild/ini/chatmail.ini.f`

### ISSUE THREAD

**Issue by abixadamj** [deltachat/chatmail#391]
When I made `git pull` and `cmdeploy run`, the file `/chatmaild/src/chatmaild/ini/chatmail.ini.f` did not update those on server.

- Operating System (Linux/Mac/Windows/iOS/Android): Linux ;-)
- Delta Chat Version: commit a9bdc3d1d0f8daf9bfdb45383fa892cf2188c9e9 (from today main/HEAD)
- Expected behavior: don't know
- Actual behavior: on server file `/usr/local/lib/chatmaild/chatmail.ini` stays in old version.
- Steps to reproduce the problem: just do update running instance of chatmail.

In new file I see some new options, like:
```
# if set to "True" IPv6 is disabled
disable_ipv6 = False
```

I see, that on server I don't have them, also timestamp of `chatmail.ini` is old - and in my opinion shuld be today....

**Comment by hpk42** [comment]
The local `chatmail.ini` file that you are using when executing `cmdeploy run` will be copied to its remote location. 

When you do `cmdeploy init my.domain` a new chatmail.ini file is generated with all options. 

Typically new ini options have a default value if they don't exist, which is the same value as the one generated with `init`. 

For now, it' might be best to add the missing options manually into your file -- or regenerate the chatmail.ini for your host, and adapt any settings you changed.   

closing the issue because there is no actionable item.
